### ISSUE TITLE
Define loaders in options

### ISSUE THREAD

**Issue by bultas** [webpack/enhanced-require#4]
Hi,

please can you advice me how to use loaders in options ?

I want to use Mocha testing to test modules with using webpack loaders function like jsx and css. 
Without module (or bundle) compilation is mocha tests fall on error sytax on loaded modules which is not pure javascript..(ex css or jsx)
Then i realize that best solution can be use this enhanced-require to load up modules and their required dependencies and compile with existing loaders (jsx loader, css loader,..). Then i hope that Mocha test can pass without problem..

but i dont know how to specify loaders in enhanced-require options.
I am  trying to solve similiar config as i have in webpack-config.. something like:

```
var myRequire = require("enhanced-require")(module, {
// options
recursive: true, 
loader: [
        { test: /\.css$/, loader: "style!css" },
        { test: /\.jsx$/, loader: "jsx-loader?harmony" },
        { test: /\.png/, loader: 'url?limit=100000&minetype=image/png' },
        { test: /\.jpg/, loader: 'file' }
    ]
});
var Hello = myRequire("../../src/components/Hello.jsx");
```

But this is not possible,, please can you tell me how exactly can i define loaders in enhanced-require options.

Thank you very much..

**Comment by sokra** [comment]
The enhanced-require module is pretty old... Better use webpack to compile your tests as bundle and run this with mocha...

You can try `resolve: { loaders: [...] }`...

**Comment by bultas** [comment]
Thanks for showing me a better direction..

So finally resolved with bundle compiled with webpack + mocha-loader.
For node cli testing I created another webpack config (target: "node") and then run mocha ..
(have to remove style-loader from config, otherwise error with document to write style element doesn't exist)
