### ISSUE TITLE
Add a global var named __webpack_public_path__ in order to play nice with other loaders (file-loader)

### ISSUE THREAD

**Issue by bitplanets** [webpack/enhanced-require#8]
Related to: https://github.com/webpack/file-loader/issues/2

**Comment by sokra** [comment]
The loader should take care of this... A `publicPath` is not something that is known in enhanced-require.

**Comment by bitplanets** [comment]
I don't really like to use that global var, but I see that many loaders use that.

> The loader should take care of this

Then the loader should know/read about enhanced-require settings?

> A publicPath is not something that is known in enhanced-require.

It could be. I pass the same options as webpack to the enhanced-require on the server.
