### ISSUE TITLE
Resolver plugin not working

### ISSUE THREAD

**Issue by richardscarrott** [webpack/enhanced-require#9]
I've been having difficulty getting the Resolver plugin working with `enhanced-require` using the following config:

```
resolve: {
    root: [
        path.join(__dirname, 'www/app'),
        path.join(__dirname, 'www/bower_components')
    ]
},
plugins: [
    new webpack.ResolverPlugin(
        new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
    )
]
```

I get `cannot resolve module react in /Users/Rich/Projects/fitbit/www/app`.

I believe the `resolve.root` config is working as if I modify the require string to point directly to the component, e.g. `require('react')` becomes `require('react/react')`, then it correctly finds it in bower_components (because it doesn't need to read the bower.json).

I have been able to get it to work by using npm instead of bower as it just automatically reads package.json... are plugins supported using enhanced require?

**Comment by sokra** [comment]
> are plugins supported using enhanced require?

no, and it's a webpack plugin...

**Comment by sokra** [comment]
I think `options.resolve` is also not supported...

It's only node.js style resolve...

**Comment by richardscarrott** [comment]
I think I'm perhaps misusing enhanced-require; I'm attempting to write an isomorphic web app where the initial html is rendered on the server for seo and faster load times.

I originally tried running the bundled src from the client side app using node's require however because the bundle doesn't export anything I had no way of retrieving the generated html string other than storing it on a global.

I then came across this project which I imagined I could use in a similar manner to requirejs in node whereby you'd require in the (non-bundled) src code however it seems enhanced-require doesn't have feature parity with webpack so I can't run the same code as on the client?

Is enhanced-require designed for this use-case or is it designed to be independent from webpack and just offers a, well, enhanced require for node?

**Comment by akiran** [comment]
@richardscarrott, did you find a solution to this problem 

I also ran into this issue 
http://stackoverflow.com/questions/28275775/how-to-handle-window-object-on-nodejs-for-server-side-rendering-of-reactjs-appli

I am also trying to implement isomorphic react application and use webpack for client side build.
I am trying to use enhanced-require to handle jsx files on nodejs.

But, imports of libraries that use window object are failing. To overcome this problem I tried to use IgnorePlugin. It looks like webpack plugins doesn't work with enhanced-require

@sokra Do you have any suggestions for this usecase.

**Comment by sokra** [comment]
> @sokra Do you have any suggestions for this usecase.

Compile with `webpack --target node` and run the compiled version...

**Comment by richardscarrott** [comment]
I see you have a good example of this here - https://github.com/webpack/react-webpack-server-side-example, thanks!
